name: Atualizar README automaticamente

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Atualizar Skills automaticamente
        run: |
          npm init -y
          node update_skills.js

      - name: Atualizar atividades recentes
        uses: JamesIves/github-activity-readme@v0.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit e Push
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Atualizar README automaticamente" || echo "Sem mudanças"
          git push
